INSERT INTO USERS (username, password, role, has_voted, first_name, last_name, pesel) VALUES ('user2', '$2a$10$SQoysXqwc4PRM69B5dREiu0KyK7mSlY8Jj65Dg7jWeVqnnqaNsLt.', 'USER', false, 'Paweł', 'Konopski', '90010254123');
INSERT INTO USERS (username, password, role, has_voted, first_name, last_name, pesel) VALUES ('user3', '$2a$10$.GqJ9nycIrQIU8cWR3ygEe1JNsPNZ/M1ksruFfDRzB1Qa5G5G0tbm', 'USER', false, 'Alicja', 'Koralik', '90044254321');
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (2, 'user12345', '$2a$10$SvcT2pdsn5ndUfkfSvtFZ.dlYk/jnKfOz/gyq0yQdl58miFuAi23e', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (2, 'user', '$2a$10$SvcT2pdsn5ndUfkfSvtFZ.dlYk/jnKfOz/gyq0yQdl58miFuAi23e', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (2, 'user', '$2a$10$SvcT2pdsn5ndUfkfSvtFZ.dlYk/jnKfOz/gyq0yQdl58miFuAi23e', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (2, 'user', '$2a$10$SvcT2pdsn5ndUfkfSvtFZ.dlYk/jnKfOz/gyq0yQdl58miFuAi23e', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (2, 'user', '$2a$10$SvcT2pdsn5ndUfkfSvtFZ.dlYk/jnKfOz/gyq0yQdl58miFuAi23e', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (54, 'user50', '$2a$10$A4ZFEZPaPcPxp.FruQQ8XuYzpdJnPZ./75EFkGPswNwhM/PA2hWgO', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (55, 'rafal', '$2a$10$AzrJoSST0HlyV/BEQV.R6evw4jqbz3Y.oH8CDQ/9UypqhnehIFQa2', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (55, 'rafal', '$2a$10$AzrJoSST0HlyV/BEQV.R6evw4jqbz3Y.oH8CDQ/9UypqhnehIFQa2', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (56, 'rafal', '$2a$10$buh5czrh3xK2ccUOeS.FhePz.jgk9DSRWyEcO8EVErheSXaV/wZTC', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (56, 'rafal', '$2a$10$buh5czrh3xK2ccUOeS.FhePz.jgk9DSRWyEcO8EVErheSXaV/wZTC', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (56, 'rafalek', '$2a$10$buh5czrh3xK2ccUOeS.FhePz.jgk9DSRWyEcO8EVErheSXaV/wZTC', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (57, 'rafal', '$2a$10$O7wQj/uIMFHdqifMmBU/sujkCMbvT09NpPL27H7GYBnBEPyZqLy96', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (59, '1234512', '$2a$10$XeccQfeS3fxmssujlA6NP.5NYhHFFoerX4FJ/EuTAfg.rxOkGjUmG', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (59, '1234512', '$2a$10$XeccQfeS3fxmssujlA6NP.5NYhHFFoerX4FJ/EuTAfg.rxOkGjUmG', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (60, 'abc2', '$2a$10$c0pcHMdq3hD48ZM4gjbk2eUiz2WncLZTQG3WWCNKfBFDii9QHwjrG', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (60, 'abc2', '$2a$10$c0pcHMdq3hD48ZM4gjbk2eUiz2WncLZTQG3WWCNKfBFDii9QHwjrG', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (60, 'abc2', '$2a$10$c0pcHMdq3hD48ZM4gjbk2eUiz2WncLZTQG3WWCNKfBFDii9QHwjrG', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (54, 'user50', '$2a$10$A4ZFEZPaPcPxp.FruQQ8XuYzpdJnPZ./75EFkGPswNwhM/PA2hWgO', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (61, '12345', '$2a$10$BsibPmYAZnJpM77qhBUpRuUuRQr6mmqe.oyYbCzYPb714J6WGA1o.', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (62, 'rafal123', '$2a$10$M0/5dT5NujYq.hebCp7mJu2cLn4rdHy3cUhjN5Ax5WqRqkgy0hHDe', 'USER', false);
INSERT INTO USERS (id, username, password, role, has_voted) VALUES (1, 'admin', '$2a$10$dj9eHfuT2oAOd4H0LabcZexzBX7MS7/NgfhabawxQpXd57ZAr3nEq', 'ADMIN', false);
